
spring.application.name=marketplace-backend


spring.datasource.url=jdbc:postgresql://127.0.0.1:5472/beautysalondb
spring.datasource.username=Del8a
spring.datasource.password=del8almond
spring.jpa.show-sql=true
